# Generated by Django 2.0.7 on 2018-10-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreport',
            name='reason',
            field=models.CharField(choices=[(1, 'spam'), (2, 'violence')], default=None, max_length=2),
        ),
    ]
