# Generated by Django 2.0.7 on 2018-11-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20181022_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreport',
            name='reason',
            field=models.CharField(choices=[('SPAM', 'spam'), ('VIOLENCE', 'violence')], default=None, max_length=255),
        ),
    ]
