# Generated by Django 2.0.7 on 2018-12-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='facebook',
            field=models.URLField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='instagram',
            field=models.URLField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='twitter',
            field=models.URLField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='youtube',
            field=models.URLField(blank=True, default='', max_length=50, null=True),
        ),
    ]
