# Generated by Django 2.0.7 on 2018-12-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181201_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='facebook',
            field=models.URLField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='instagram',
            field=models.URLField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='twitter',
            field=models.URLField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='youtube',
            field=models.URLField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
