# Generated by Django 2.0.7 on 2018-08-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180724_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_since',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
