# Generated by Django 2.0.7 on 2018-08-10 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_time_since'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created',)},
        ),
    ]
