# Generated by Django 2.0.6 on 2018-06-06 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fun', '0002_auto_20180604_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
