# Generated by Django 2.0.7 on 2018-10-22 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20180726_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecomment',
            options={'ordering': ('created',)},
        ),
    ]
